name: s_api_v2
version: 0.0.1
description: A simple console application.
dependencies:
  logging: 'any'
  rpc: 'any'
  dartson: 'any'
  mongo_dart: '0.2.10'
  json_object: '1.0.19'
transformers:
- dartson