name: s_api_v2
version: 0.0.1
description: A simple console application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  logging: 'any'
  rpc: '0.5.7'
  dartson: 'any'
  mongo_dart: 'any'
  json_object: '1.0.19'
  connection_pool: '0.1.2'
transformers:
- dartson